// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiM2Ga9AHNKWqrnHMs9LguNXa6rR2g2fA',
    appId: '1:1027111466832:web:99f2597758fdc0628d5e55',
    messagingSenderId: '1027111466832',
    projectId: 'flaconi-a3b67',
    authDomain: 'flaconi-a3b67.firebaseapp.com',
    storageBucket: 'flaconi-a3b67.appspot.com',
    measurementId: 'G-9YHX3NHZ9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_loKXuec9yaygyy69OKaOVE7knpJ93H0',
    appId: '1:1027111466832:android:4dfd8e52027d067b8d5e55',
    messagingSenderId: '1027111466832',
    projectId: 'flaconi-a3b67',
    storageBucket: 'flaconi-a3b67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHYuuE6l5QPOOLJalgqsYpGFO_MP346mU',
    appId: '1:1027111466832:ios:14a97edb4a7cb0e38d5e55',
    messagingSenderId: '1027111466832',
    projectId: 'flaconi-a3b67',
    storageBucket: 'flaconi-a3b67.appspot.com',
    iosClientId: '1027111466832-b20m1hl9u8iousrt7jjd45iulab376ai.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicApp',
  );
}
